from tkinter import *
root = Tk()
root.title("app")
root.geometry("400x400+300+100")
root.grid_columnconfigure ((0,1,2,3,4), weight = 1 )
def clear():
    my_entry.delete(0,END)
    my_entry1.delete(0,END)
    my_entry2.delete(0,END)
    my_entry3.delete(0,END)
gender_var = IntVar(value = 1)    
def save_data():
    age = my_entry.get()
    name = my_entry1.get()
    date = my_entry2.get()
    number = my_entry3.get()
    gender = "Male" if gender_var.get() == 1 else "Not specified"
    
    print(f"Name: {name}")
    print(f"Age: {age}")
    print(f"Date: {date}")
    print(f"Number: {number}")
    print(f"Gender: {gender}")
print ("done")
my_label = Label(root, text= "enter your data", fg = "white", bg = "black",font = ("Segoe UI",12,"bold"),padx = 10, pady = 2)
my_label.grid(row =0 , column =0,columnspan =4)
my_label1 = Label(root, text = "enter your age:",padx = 5)
my_label1.grid(row = 1, column=0,sticky = "w",pady = 10,padx = 5)
my_entry = Entry(root)
my_entry.grid(row = 1 , column =1,sticky = "w",pady = 10 )
my_label2  =Label (root , text = "enter your name:")
my_label2.grid (row = 1, column = 2 )
my_entry1 = Entry (root)
my_entry1.grid (row = 1 , column = 3)
my_label3 = Label(root,text = "  enter your date:",padx = 5)
my_label3.grid(row = 2 , column = 0 , pady = 10,padx =5)
my_entry2 = Entry (root)
my_entry2.grid (row  =  2 , column = 1)
my_label4 = Label (root, text = "    enter your number:  ",)
my_label4.grid(row = 2 , column = 2,padx = 5)
my_entry3 = Entry (root)
my_entry3.grid(row=2,column=3)
rd_b = Radiobutton (root, text = "male", value = 1 )
rd_b.place(x = 130 , y = 100)
rd_b2 = Radiobutton (root ,  text = "female" , value = 2)
rd_b2.place(x = 190 , y = 100)
my_button = Button(root, text = "Save", padx = 10 , pady = 2,command = save_data  )
my_button.grid(row = 3 , column = 0,sticky ="e",pady = 20,columnspan = 2)
my_button1 = Button (root , text = "cancel ", padx = 5 , pady = 2 , command = exit)
my_button1.grid(row = 3 , column = 2,sticky ="w",pady =20 , columnspan=2 )
mybutton2 = Button(root, text = "Clear",padx = 5 ,pady = 2,command=clear)
mybutton2.place(x = 245 , y = 131)
root.mainloop()
